<?php

namespace Epigra\NovaSettings\DTO\NovaSetting;

use Carbon\Carbon;
use Epigra\Core\DTO\Base\BaseDTO;
use Illuminate\Validation\Rule;

/**
 * Class NovaSettingDTO
 */
class NovaSettingDTO extends BaseDTO
{
    /**
     * SlideDTO constructor.
     * @param array $parameters
     */
    public function __construct(array $parameters = [])
    {
        parent::__construct($parameters, self::class);
    }

    /**
     * @var int
     */
    public int $id;

    /**
     * @var string
     */
    public string $key;

    /**
     * @var string
     */
    public string $value;

    public function mapToDTO($dto, array $originalData): BaseDTO
    {
        return parent::mapToDTO($dto, $originalData); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $parameters
     * @param bool $updateMode
     * @return array
     */
    public function validate(array $parameters, bool $updateMode)
    {
        return $this->validator($parameters, [
            //'title' => 'required|string|max:255',
        ]);
    }
}
